// // app/layout.jsx
// // import "./globals.css";
// // import Header from "@/components/Header";
// // import { homeNav } from "@/components/layout/navLinks";

// // export const metadata = {
// //   title: "Home | MyJob",
// //   description: "Job portal home page",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body className="antialiased">
// //         <Header menuLinks={homeNav} />
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }

// // app/layout.jsx

// // "use client";

// import Footer from "./components/layouts/Footer";
// import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="antialiased">
//         {/* <Header /> This component can use usePathname internally */}
//         <main>{children}</main>
//         <Footer />
//       </body>
//     </html>
//   );
// }

// app/layout.jsx
// import Footer from "./components/layouts/Footer";
// import "./globals.css";

// export const metadata = {
//   title: "MyJob - Find Your Dream Job",
//   description: "Job portal application",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="antialiased">
//         <main>{children}</main>
//         {/* Footer will be conditionally rendered in the (auth) layout */}
//         <Footer />
//       </body>
//     </html>
//   );
// }

// app/layout.jsx

"use client";

import { useSelectedLayoutSegment } from "next/navigation";
import Footer from "./components/layouts/Footer";
import "./globals.css";

export default function RootLayout({ children }) {
  const segment = useSelectedLayoutSegment();
  const isAuthRoute = segment === "(auth)";

  return (
    <html lang="en">
      <body className="antialiased">
        <main>{children}</main>
        {!isAuthRoute && <Footer />}
      </body>
    </html>
  );
}
