import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />
        {children}

        {/* <div className="py-4 px-6   mx-auto"></div> */}
      </body>
    </html>
  );
}
